# Generated by Django 4.2.2 on 2023-06-16 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortner_api", "0002_url_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
